# Generated by Django 6.0.2 on 2026-02-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='otp_fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
